#define MENSAJE_LLEGA "llega"
#define MENSAJE_ESTABA "estaba"
#define MENSAJE_INICIAR "iniciar"
#define MENSAJE_ID "ID"
#define MENSAJE_SOS_PRIMERO "sos_primero"
#define MENSAJE_NO_SOS_PRIMERO "no_sos_primero"

#define MENSAJE_KEY_1 "key_1"
#define MENSAJE_KEY_2 "key_2"
#define MENSAJE_KEY_3 "key_3"
#define MENSAJE_KEY_4 "key_4"
#define MENSAJE_KEY_5 "key_5"
#define MENSAJE_KEY_UP "key_up"
#define MENSAJE_KEY_DN "key_dn"
#define MENSAJE_KEY_RIGHT "key_rt"
#define MENSAJE_KEY_LEFT "key_lt"
#define MENSAJE_KEY_Z "key_z"
#define MENSAJE_KEY_X "key_x"
