#define MENSAJE_LLEGA "llega"
#define MENSAJE_ESTABA "estaba"
#define MENSAJE_INICIAR "iniciar"
#define MENSAJE_ID "ID"

#define MENSAJE_POSICION "sos_posicion"

#define MENSAJE_SOS_PRIMERO "sos_primero"
#define MENSAJE_NO_SOS_PRIMERO "no_sos_primero"

#define MENSAJE_KEY_1 "key_1"
#define MENSAJE_KEY_2 "key_2"
#define MENSAJE_KEY_3 "key_3"
#define MENSAJE_KEY_4 "key_4"
#define MENSAJE_KEY_5 "key_5"
#define MENSAJE_KEY_UP "key_up"
#define MENSAJE_KEY_DN "key_dn"
#define MENSAJE_KEY_RIGHT "key_rt"
#define MENSAJE_KEY_LEFT "key_lt"
#define MENSAJE_KEY_Z "key_z"
#define MENSAJE_KEY_X "key_x"

#define MENSAJE_KEY_UP_LIBERADA		"key_up_liberada"
#define MENSAJE_KEY_DN_LIBERADA		"key_dn_liberada"
#define MENSAJE_KEY_RIGHT_LIBERADA	"key_rt_liberada"
#define MENSAJE_KEY_LEFT_LIBERADA	"key_lt_liberada"

#define MENSAJE_INICIAR_ENVIO_FULLSNAPSHOT	"iniciar_envio_fs"
#define MENSAJE_ENVIO_SNAPSHOT				"viene_snapshot"
#define MENSAJE_TERMINAR_ENVIO_FULLSNAPSHOT	"terminar_envio_fs"
