#ifndef DEFINICIONES
#define DEFINICIONES

#include <exception>
#include "Cadena.h"

#define DISTANCIAVISION 15

#define NULO 0

#define FANTASMAS 0
#define CONSTRUCCIONES 1
#define ENEMIGOS 2
#define PERSONAJES 4
#define POWERUPS 8
#define DISPAROS 16
#define ESCALERAS 32
#define JUMPBOX 64
#define CAJASACCION 128
#define LEFTBOX 256
#define RIGHTBOX 512
#define AURAENEMIGOS 1024

#define BOMBA 1

#define IDCONSTRUCCIONES 0

#define MAXIMALONGITUDBUFFER 1000

#define GRAVEDAD 10
#define ANCHOESCALERA 1.1
#define ANCHOPUERTA 0.25
#define ALTOPUERTA 15.0

#define ENERGIAMEGAMAN 200
#define MASAMEGAMAN 57
#define MAXIMACANTIDADPLASMA 50
#define CANTIDADINFINITAPLASMA -1
#define MAXIMACANTIDADVIDAS 127
#define VIDASINICIALES 3
#define DANOPORCONTACTO 5

#define CUERPOPRINCIPAL 0
#define MEGAMANJUMPBOX 1

#define VELOCIDADMEGAMANCORRIENDO 2
#define VELOCIDADMEGAMANESCALERA 2
#define POSICIONDISPAROMEGAMAN 0.8
#define POSICIONLANZAMIENTOMEGAMAN 1.6
#define VELOCIDADSALTOMEGAMAN 6
#define TIEMPOINMUNIDADMEGAMAN 3

#define ANCHOSPRITEMEGAMAN 0.8
#define ALTOSPRITEMEGAMAN 1.6

#define MASAPOWERUP 10
#define VELOCIDADPOWERUP (0,-5)
#define ANCHOSPRITEPOWERUP 0.5
#define ALTOSPRITEPOWERUP 0.5

#define ENERGIAMAXIMABUMBY 10
#define MASABUMBY 50
#define ANCHOBUMBY 0.5
#define ALTOBUMBY 0.5
#define VELOCIDADSALTOBUMBY 0
#define VELOCIDADCORRERBUMBY 1

#define ENERGIAMAXIMAMET 100
#define MASAMET 50
#define ESCUDOMET 50
#define ANCHOMET 0.5
#define ALTOMET 0.5
#define VELOCIDADSALTOMET 0
#define VELOCIDADCORRERMET 0

#define ENERGIAMAXIMASNIPER 100
#define MASASNIPER 50
#define ESCUDOSNIPER 50
#define ANCHOSNIPER 0.5
#define ALTOSNIPER 0.5
#define VELOCIDADSALTOSNIPER 0
#define VELOCIDADCORRERSNIPER 0

#define ENERGIAMAXIMAJUMPINGSNIPER 100
#define MASAJUMPINGSNIPER 50
#define ESCUDOJUMPINGSNIPER 50
#define ANCHOJUMPINGSNIPER 0.5
#define ALTOJUMPINGSNIPER 0.5
#define VELOCIDADSALTOJUMPINGSNIPER 0
#define VELOCIDADCORRERJUMPINGSNIPER 0

#define ENERGIAMAXIMABOMBMAN 100
#define MASABOMBMAN 50
#define ESCUDOBOMBMAN 0
#define ANCHOBOMBMAN 1
#define ALTOBOMBMAN 2
#define VELOCIDADSALTOBOMBMAN 10
#define VELOCIDADCORRERBOMBMAN 2


#define PROBANUEVAVIDA 0.01f
#define PROBAENERGIACHICA 0.1f
#define PROBAENERGIAGRANDE 0.05f
#define PROBAPLASMACHICA 0.1f
#define PROBAPLASMAGRANDE 0.05f

#define RADIOEXPLOSION 1.5
#define TIEMPOEXPLOSIONBOMBA 5
#define DANOBOMBA 20
#define MASABOMBA 5
#define MULTIPLICADORVELOCIDADBOMBA 3
#define ANCHOSPRITEBOMBA 0.5
#define ALTOSPRITEBOMBA 0.5

#define DANOPLASMA 15
#define MASAPLASMA 1
#define MULTIPLICADORVELOCIDADPLASMA 7
#define ANCHOSPRITEPLASMA 0.2
#define ALTOSPRITEPLASMA 0.2

#define DANOCHISPA 15
#define MASACHISPA 1
#define MULTIPLICADORVELOCIDADCHISPA 7
#define ANCHOSPRITECHISPA 1
#define ALTOSPRITECHISPA 1

#define DANOANILLO 15
#define MASAANILLO 1
#define MULTIPLICADORVELOCIDADANILLO 7
#define ANCHOSPRITEANILLO 1
#define ALTOSPRITEANILLO 1
#define TIEMPOANILLO 5

#define DANOFUEGO 15
#define MASAFUEGO 1
#define MULTIPLICADORVELOCIDADFUEGO 7
#define ANCHOSPRITEFUEGO 1
#define ALTOSPRITEFUEGO 1

#define DANOIMAN 15
#define MASAIMAN 1
#define MULTIPLICADORVELOCIDADIMAN 7
#define ANCHOSPRITEIMAN 0.25
#define ALTOSPRITEIMAN 0.25
#define IMPULSOIMAN 1

typedef unsigned int uint;
typedef float real;
typedef unsigned short ushort;
/////////////////////////////////////////////////////////////////////////
class NoPudoCrearseConexion : public std::exception {};
class NoHayConexion : public std::exception {};
class ErrorEnLaConexion : public std::exception {};
class EstadoParametroIncorrecto : public std::exception {};
class ClaveInvalida : public std::exception {};
class ParametroEsPunteroNulo : public std::exception {};
class NoPudoLanzarseHilo : public std::exception {};

#endif
