#include "Definiciones.h"

namespace SJuego
{
	Constantes attr;

	void Constantes::cargar(std::string nombreArchivo)
	{
		 AGREGARMAPA(distanciavision)
		 AGREGARMAPA(bomba)
		 AGREGARMAPA(idconstrucciones)
		 AGREGARMAPA(maximalongitudbuffer)
		 AGREGARMAPA(gravedad)
		 AGREGARMAPA(anchoescalera)
		 AGREGARMAPA(anchopuerta)
		 AGREGARMAPA(altopuerta)
		 AGREGARMAPA(energiamegaman)
		 AGREGARMAPA(masamegaman)
		 AGREGARMAPA(maximacantidadplasma)
		 AGREGARMAPA(cantidadinfinitaplasma)
		 AGREGARMAPA(maximacantidadvidas)
		 AGREGARMAPA(vidasiniciales)
		 AGREGARMAPA(danoporcontacto)
		 AGREGARMAPA(cuerpoprincipal)
		 AGREGARMAPA(megamanjumpbox)
		 AGREGARMAPA(velocidadmegamancorriendo)
		 AGREGARMAPA(velocidadmegamanescalera)
		 AGREGARMAPA(posiciondisparomegaman)
		 AGREGARMAPA(posicionlanzamientomegaman)
		 AGREGARMAPA(velocidadsaltomegaman)
		 AGREGARMAPA(tiempoinmunidadmegaman)
		 AGREGARMAPA(anchospritemegaman)
		 AGREGARMAPA(altospritemegaman)
		 AGREGARMAPA(masapowerup)
		 AGREGARMAPA(velocidadpowerup)
		 AGREGARMAPA(anchospritepowerup)
		 AGREGARMAPA(altospritepowerup)
		 AGREGARMAPA(energiamaximabumby)
		 AGREGARMAPA(masabumby)
		 AGREGARMAPA(anchobumby)
		 AGREGARMAPA(altobumby)
		 AGREGARMAPA(velocidadsaltobumby)
		 AGREGARMAPA(velocidadcorrerbumby)
		 AGREGARMAPA(energiamaximamet)
		 AGREGARMAPA(masamet)
		 AGREGARMAPA(escudomet)
		 AGREGARMAPA(anchomet)
		 AGREGARMAPA(altomet)
		 AGREGARMAPA(velocidadsaltomet)
		 AGREGARMAPA(velocidadcorrermet)
		 AGREGARMAPA(energiamaximasniper)
		 AGREGARMAPA(masasniper)
		 AGREGARMAPA(escudosniper)
		 AGREGARMAPA(anchosniper)
		 AGREGARMAPA(altosniper)
		 AGREGARMAPA(velocidadsaltosniper)
		 AGREGARMAPA(velocidadcorrersniper)
		 AGREGARMAPA(energiamaximajumpingsniper)
		 AGREGARMAPA(masajumpingsniper)
		 AGREGARMAPA(escudojumpingsniper)
		 AGREGARMAPA(anchojumpingsniper)
		 AGREGARMAPA(altojumpingsniper)
		 AGREGARMAPA(velocidadsaltojumpingsniper)
		 AGREGARMAPA(velocidadcorrerjumpingsniper)
		 AGREGARMAPA(energiamaximabombman)
		 AGREGARMAPA(masabombman)
		 AGREGARMAPA(escudobombman)
		 AGREGARMAPA(anchobombman)
		 AGREGARMAPA(altobombman)
		 AGREGARMAPA(velocidadsaltobombman)
		 AGREGARMAPA(velocidadcorrerbombman)
		 AGREGARMAPA(energiamaximasparkman)
		 AGREGARMAPA(masasparkman)
		 AGREGARMAPA(escudosparkman)
		 AGREGARMAPA(anchosparkman)
		 AGREGARMAPA(altosparkman)
		 AGREGARMAPA(velocidadsaltosparkman)
		 AGREGARMAPA(velocidadcorrersparkman)
 		 AGREGARMAPA(energiamaximamagnetman)
		 AGREGARMAPA(masamagnetman)
		 AGREGARMAPA(escudomagnetman)
		 AGREGARMAPA(anchomagnetman)
		 AGREGARMAPA(altomagnetman)
		 AGREGARMAPA(velocidadsaltomagnetman)
		 AGREGARMAPA(velocidadcorrermagnetman)

		 AGREGARMAPA(energiamaximaringman)
		 AGREGARMAPA(masaringman)
		 AGREGARMAPA(escudoringman)
		 AGREGARMAPA(anchoringman)
		 AGREGARMAPA(altoringman)
		 AGREGARMAPA(velocidadsaltoringman)
		 AGREGARMAPA(velocidadcorrerringman)

	 	 AGREGARMAPA(energiamaximafireman)
		 AGREGARMAPA(masafireman)
		 AGREGARMAPA(escudofireman)
		 AGREGARMAPA(anchofireman)
		 AGREGARMAPA(altofireman)
		 AGREGARMAPA(velocidadsaltofireman)
		 AGREGARMAPA(velocidadcorrerfireman)

		 AGREGARMAPA(probanuevavida)
		 AGREGARMAPA(probaenergiachica)
		 AGREGARMAPA(probaenergiagrande)
		 AGREGARMAPA(probaplasmachica)
		 AGREGARMAPA(probaplasmagrande)
		 AGREGARMAPA(radioexplosion)
		 AGREGARMAPA(tiempoexplosionbomba)
		 AGREGARMAPA(danobomba)
		 AGREGARMAPA(masabomba)
		 AGREGARMAPA(multiplicadorvelocidadbomba)
		 AGREGARMAPA(anchospritebomba)
		 AGREGARMAPA(altospritebomba)
		 AGREGARMAPA(danoplasma)
		 AGREGARMAPA(masaplasma)
		 AGREGARMAPA(multiplicadorvelocidadplasma)
		 AGREGARMAPA(anchospriteplasma)
		 AGREGARMAPA(altospriteplasma)
		 AGREGARMAPA(danochispa)
		 AGREGARMAPA(masachispa)
		 AGREGARMAPA(multiplicadorvelocidadchispa)
		 AGREGARMAPA(anchospritechispa)
		 AGREGARMAPA(altospritechispa)
		 AGREGARMAPA(danoanillo)
		 AGREGARMAPA(masaanillo)
		 AGREGARMAPA(multiplicadorvelocidadanillo)
		 AGREGARMAPA(anchospriteanillo)
		 AGREGARMAPA(altospriteanillo)
		 AGREGARMAPA(tiempoanillo)
		 AGREGARMAPA(danofuego)
		 AGREGARMAPA(masafuego)
		 AGREGARMAPA(multiplicadorvelocidadfuego)
		 AGREGARMAPA(anchospritefuego)
		 AGREGARMAPA(altospritefuego)
		 AGREGARMAPA(danoiman)
		 AGREGARMAPA(masaiman)
		 AGREGARMAPA(multiplicadorvelocidadiman)
		 AGREGARMAPA(anchospriteiman)
		 AGREGARMAPA(altospriteiman)
		 AGREGARMAPA(impulsoiman)

		Cadena linea("");
		std::string nombre;
		std::vector<Cadena> partes;

		std::fstream archivo;
		archivo.open(nombreArchivo, std::ios::in);

		while(!archivo.eof())
		{
			archivo >> linea;
			partes = linea.partir(Cadena("="));
			
			*punteros[partes.at(0)] = (double)partes.at(2);
		}

	}
}
